from . import event_compassion
from . import crowdfunding_participant
from . import crowdfunding_project
from . import product_template
from . import account_move_line
from . import res_partner
from . import staff_notification_settings
from . import account_move
from . import product_product
from . import res_partner_match
from . import sale_order_line
